# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: index.proto
# plugin: python-betterproto
# This file has been @generated

from dataclasses import dataclass
from typing import (
    List,
    Optional,
)

import betterproto


class ContentWarning(betterproto.Enum):
    UNSPECIFIED = 0
    SAFE = 1
    MIXED = 2
    NSFW = 3


@dataclass(eq=False, repr=False)
class Index(betterproto.Message):
    name: str = betterproto.string_field(1)
    badge_label: str = betterproto.string_field(2)
    signing_key: str = betterproto.string_field(3)
    contact: "Contact" = betterproto.message_field(4)
    extension_list: "ExtensionList" = betterproto.message_field(101, group="extensions")
    extension_list_url: str = betterproto.string_field(102, group="extensions")


@dataclass(eq=False, repr=False)
class Contact(betterproto.Message):
    website: str = betterproto.string_field(1)
    discord: Optional[str] = betterproto.string_field(2, optional=True)


@dataclass(eq=False, repr=False)
class ExtensionList(betterproto.Message):
    extensions: List["Extension"] = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class Extension(betterproto.Message):
    name: str = betterproto.string_field(1)
    package_name: str = betterproto.string_field(2)
    resources: "Resources" = betterproto.message_field(3)
    extension_lib: str = betterproto.string_field(4)
    version_code: int = betterproto.int64_field(5)
    version_name: str = betterproto.string_field(6)
    content_warning: "ContentWarning" = betterproto.enum_field(7)
    sources: List["Source"] = betterproto.message_field(8)


@dataclass(eq=False, repr=False)
class Resources(betterproto.Message):
    apk_url: str = betterproto.string_field(1)
    icon_url: str = betterproto.string_field(2)
    jar_url: str = betterproto.string_field(501)


@dataclass(eq=False, repr=False)
class Source(betterproto.Message):
    id: int = betterproto.int64_field(1)
    name: str = betterproto.string_field(2)
    language: str = betterproto.string_field(3)
    home_url: str = betterproto.string_field(4)
    mirror_urls: List[str] = betterproto.string_field(5)
    message: Optional[str] = betterproto.string_field(7, optional=True)
